### ISSUE TITLE
Violation of the GNU License

### ISSUE THREAD

**Issue by freemansmind** [parsec-cloud/web-client#8]
First I apologize for posting here as I could not locate the appropriate channel for reporting this. 

It seems in the past you used ScpVBus (removed [8/15/2017](https://archive.fo/m37ps#selection-9.15517-9.15547)) and it's user-mode library [which is licensed under GPL 3.0](https://github.com/nefarius/ScpVBus/blob/master/LICENSE.md), rather than [ViGEm](https://github.com/nefarius/ViGEm). If you link to a GPL library in your application, even if you later remove it, then you have created a derived work and your code must also be GPL. Given your software is distributed to users I am creating this issue as I was unable to find a portal for downloading the source code to versions of your application, which puts it in violation of the GNU license above. 

There are also some possible non-GNU license violations as your application references openh264 (I assume for software encoding/decoding) yet seems compiled from source, rather than linking Cisco's binaries which requires you to pay the MPEG-LA licensing fees.

For transparency I am submitting a copy of this report to the [Free Software Foundation](https://www.gnu.org/licenses/gpl-violation.en.html).

**Comment by chrisd1100** [comment]
We do not believe we are in violation of any license. We have a strong relationship with Nefarius who maintains both of these libraries.
